#! /usr/bin/env sh

gsettings set org.gnome.desktop.wm.preferences          mouse-button-modifier               "'<Alt>'"
gsettings set org.gnome.desktop.wm.preferences          resize-with-right-button            "true"

gsettings set org.gnome.desktop.background              show-desktop-icons                  "false"

gsettings set org.gnome.desktop.calendar                show-weekdate                       "true"

gsettings set org.gnome.desktop.input-sources           xkb-options                         "['compose:caps']"

gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-1               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-2               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-3               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-4               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-5               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-6               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-7               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-8               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-9               "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-10              "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-11              "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-12              "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-1                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-2                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-3                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-4                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-5                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-6                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-7                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-8                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-9                 "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-10                "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-11                "[]"
gsettings set org.gnome.desktop.wm.keybindings          move-to-workspace-12                "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-down            "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-last            "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-to-workspace-up              "[]"
gsettings set org.gnome.desktop.wm.keybindings          switch-windows                      "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings          switch-windows-backward             "['<Shift><Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings          toggle-above                        "[]"
gsettings set org.gnome.desktop.wm.keybindings          toggle-fullscreen                   "['<Alt>F11']"
gsettings set org.gnome.desktop.wm.keybindings          toggle-maximized                    "['<Alt>F10', '<Primary><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings          toggle-on-all-workspaces            "[]"
gsettings set org.gnome.desktop.wm.keybindings          unmaximize                          "[]"
gsettings set org.gnome.desktop.wm.keybindings          begin-move                          "['<Alt>F7']"
gsettings set org.gnome.desktop.wm.keybindings          begin-resize                        "['<Alt>F8']"
gsettings set org.gnome.desktop.wm.keybindings          close                               "['<Primary>q']"

gsettings set org.gnome.mutter                          dynamic-workspaces                  "false"
gsettings set org.gnome.mutter.keybindings              toggle-tiled-left                   "['<Control><Super>Left']"
gsettings set org.gnome.mutter.keybindings              toggle-tiled-right                  "['<Control><Super>Right']"

gsettings set org.gnome.shell.keybindings               focus-active-notification           "[]"
gsettings set org.gnome.shell.keybindings               shift-overview-down                 "['<Super><Alt>Down']"
gsettings set org.gnome.shell.keybindings               shift-overview-up                   "['<Super><Alt>Up']"
gsettings set org.gnome.shell.keybindings               show-screen-recording-ui            "['<Ctrl><Shift><Alt>R']"
gsettings set org.gnome.shell.keybindings               show-screenshot-ui                  "['Print']"
gsettings set org.gnome.shell.keybindings               switch-to-application-1             "['<Super>1']"
gsettings set org.gnome.shell.keybindings               switch-to-application-2             "['<Super>2']"
gsettings set org.gnome.shell.keybindings               switch-to-application-3             "['<Super>3']"
gsettings set org.gnome.shell.keybindings               switch-to-application-4             "['<Super>4']"
gsettings set org.gnome.shell.keybindings               switch-to-application-5             "['<Super>5']"
gsettings set org.gnome.shell.keybindings               switch-to-application-6             "['<Super>6']"
gsettings set org.gnome.shell.keybindings               switch-to-application-7             "['<Super>7']"
gsettings set org.gnome.shell.keybindings               switch-to-application-8             "['<Super>8']"
gsettings set org.gnome.shell.keybindings               switch-to-application-9             "['<Super>9']"
gsettings set org.gnome.shell.keybindings               toggle-application-view             "['<Super>a']"
gsettings set org.gnome.shell.keybindings               toggle-message-tray                 "['<Super>v','<Super>m']"
gsettings set org.gnome.shell.keybindings               toggle-overview                     "['<Super>s']"

gsettings set org.gnome.shell.app-switcher              current-workspace-only              "false"

gsettings set org.gnome.settings-daemon.plugins.power   sleep-inactive-ac-timeout           "3600"
gsettings set org.gnome.settings-daemon.plugins.power   sleep-inactive-ac-type              "'nothing'"

gsettings set org.gnome.settings-daemon.plugins.media-keys    screensaver                   "['<Super>l']"
gsettings set org.gnome.settings-daemon.plugins.media-keys    home                          "['<Super>h']"
gsettings set org.gnome.settings-daemon.plugins.media-keys    calculator                    "['<Super>c']"

gsettings set org.gnome.desktop.interface                clock-show-seconds                 "true"
gsettings set org.gnome.desktop.interface                clock-show-weekday                 "true"
gsettings set org.gnome.desktop.interface                clock-show-date                    "true"

gsettings set org.gnome.desktop.screensaver              lock-delay                         "uint32 3600"

gsettings set org.gnome.desktop.search-providers         disable-external                   "true"

gsettings set org.gnome.desktop.privacy                  remove-old-temp-files              "true"
gsettings set org.gnome.desktop.privacy                  old-files-age                      "uint32 14"
gsettings set org.gnome.desktop.privacy                  remove-old-trash-files             "true"

gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-1                       "['<Super>1']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-2                       "['<Super>2']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-3                       "['<Super>3']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-4                       "['<Super>4']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-5                       "['<Super>5']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-6                       "['<Super>6']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-7                       "['<Super>7']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-8                       "['<Super>8']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-9                       "['<Super>9']"
gsettings set org.gnome.shell.extensions.dash-to-dock    app-hotkey-10                      "['<Super>0']"
gsettings set org.gnome.shell.extensions.dash-to-dock    disable-overview-on-startup        "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    hot-keys                           "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    hotkeys-overlay                    "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    hotkeys-show-dock                  "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    multi-monitor                      "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    scroll-action                      "'do-nothing'"
gsettings set org.gnome.shell.extensions.dash-to-dock    scroll-switch-workspace            "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    scroll-to-focused-application      "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    shift-click-action                 "'minimize'"
gsettings set org.gnome.shell.extensions.dash-to-dock    shortcut                           "['<Super>q']"
gsettings set org.gnome.shell.extensions.dash-to-dock    shortcut-text                      "'<Super>q'"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-apps-at-top                   "false"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-dock-urgent-notify            "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-favorites                     "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-mounts                        "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-mounts-network                "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-mounts-only-mounted           "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-running                       "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-show-apps-button              "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-trash                         "true"
gsettings set org.gnome.shell.extensions.dash-to-dock    show-windows-preview               "false"
gsettings set org.gnome.shell.extensions.dash-to-dock    activate-single-window             "true"

gsettings set org.gnome.shell.extensions.gtile           insets-primary-left                "0"
gsettings set org.gnome.shell.extensions.gtile           show-toggle-tiling                 "['<Super>t']"
gsettings set org.gnome.shell.extensions.gtile           window-margin                      "0"

gsettings set org.gnome.gthumb.browser                   scroll-action                      "'zoom'"
